[package]
name = "sudoku_solve"
version = "0.1.0"
edition = "2021"
authors = ["Gerrit R"]

[dependencies]
csv = "1.3.0"
serde = { version = "1.0", features = ["derive"] } 
clap = {version = "4.4.8", features = ["derive"]}
